// <auto-generated />
using System;
using MediaVault.LinkHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaVault.LinkHub.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820174950_AddSuggestions")]
    partial class AddSuggestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ActressMediaFile", b =>
                {
                    b.Property<int>("ActressesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaFilesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActressesId", "MediaFilesId");

                    b.HasIndex("MediaFilesId");

                    b.ToTable("MediaFileActresses", (string)null);
                });

            modelBuilder.Entity("MediaFileProducer", b =>
                {
                    b.Property<int>("MediaFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProducersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaFilesId", "ProducersId");

                    b.HasIndex("ProducersId");

                    b.ToTable("MediaFileProducers", (string)null);
                });

            modelBuilder.Entity("MediaFileVideoCategory", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaFilesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesId", "MediaFilesId");

                    b.HasIndex("MediaFilesId");

                    b.ToTable("MediaFileCategories", (string)null);
                });

            modelBuilder.Entity("MediaVault.LinkHub.Domain.Entities.Actress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("Actresses", (string)null);
                });

            modelBuilder.Entity("MediaVault.LinkHub.Domain.Entities.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<double>("RankingCalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("RankingContenido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("RankingGusto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int>("VecesAbierto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Extension");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("VecesAbierto");

                    b.ToTable("MediaFiles", (string)null);
                });

            modelBuilder.Entity("MediaVault.LinkHub.Domain.Entities.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("Producers", (string)null);
                });

            modelBuilder.Entity("MediaVault.LinkHub.Domain.Entities.QuickNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FechaCreacion");

                    b.ToTable("QuickNotes", (string)null);
                });

            modelBuilder.Entity("MediaVault.LinkHub.Domain.Entities.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaResuelto")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Resuelto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("Resuelto");

                    b.ToTable("Suggestions", (string)null);
                });

            modelBuilder.Entity("MediaVault.LinkHub.Domain.Entities.SuggestionAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuggestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SuggestionId");

                    b.ToTable("SuggestionAttachments", (string)null);
                });

            modelBuilder.Entity("MediaVault.LinkHub.Domain.Entities.VideoCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("VideoCategories", (string)null);
                });

            modelBuilder.Entity("MediaVault.LinkHub.Domain.Entities.WebLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<double>("LogoOffsetX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("LogoOffsetY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<string>("LogoPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<double>("LogoZoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1.0);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("FechaUltimaActualizacion");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("WebLinks", (string)null);
                });

            modelBuilder.Entity("ProducerWebLink", b =>
                {
                    b.Property<int>("ProducersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WebLinksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProducersId", "WebLinksId");

                    b.HasIndex("WebLinksId");

                    b.ToTable("WebLinkProducers", (string)null);
                });

            modelBuilder.Entity("ActressMediaFile", b =>
                {
                    b.HasOne("MediaVault.LinkHub.Domain.Entities.Actress", null)
                        .WithMany()
                        .HasForeignKey("ActressesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaVault.LinkHub.Domain.Entities.MediaFile", null)
                        .WithMany()
                        .HasForeignKey("MediaFilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaFileProducer", b =>
                {
                    b.HasOne("MediaVault.LinkHub.Domain.Entities.MediaFile", null)
                        .WithMany()
                        .HasForeignKey("MediaFilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaVault.LinkHub.Domain.Entities.Producer", null)
                        .WithMany()
                        .HasForeignKey("ProducersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaFileVideoCategory", b =>
                {
                    b.HasOne("MediaVault.LinkHub.Domain.Entities.VideoCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaVault.LinkHub.Domain.Entities.MediaFile", null)
                        .WithMany()
                        .HasForeignKey("MediaFilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaVault.LinkHub.Domain.Entities.SuggestionAttachment", b =>
                {
                    b.HasOne("MediaVault.LinkHub.Domain.Entities.Suggestion", "Suggestion")
                        .WithMany("Attachments")
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suggestion");
                });

            modelBuilder.Entity("ProducerWebLink", b =>
                {
                    b.HasOne("MediaVault.LinkHub.Domain.Entities.Producer", null)
                        .WithMany()
                        .HasForeignKey("ProducersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaVault.LinkHub.Domain.Entities.WebLink", null)
                        .WithMany()
                        .HasForeignKey("WebLinksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaVault.LinkHub.Domain.Entities.Suggestion", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
